version: '3.7'
services: 
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${TAG}
    container_name: elasticsearch
    ports: 
      - "9200:9200"
      - "9300:9300"
    environment: 
      # - elasticsearch.username=elastic
      # - elasticsearch.password=MyPwd123
      - node.name=elasticsearch
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - bootstrap.memory_lock=true
      - http.cors.enabled=true
      - http.cors.allow-origin=*
    volumes: 
      - /home/home/ELK/elasticsearch/data:/usr/share/elasticsearch/data
      - /home/home/ELK/elasticsearch/backups:/usr/share/elasticsearch/backups
    expose:
      - "9200"
      - "9300"

  kibana:
    image: docker.elastic.co/kibana/kibana:${TAG}
    container_name: kibana
    ports: 
      - "5601:5601"
    # environment: 
    #   - elasticsearch.username=elastic
    #   - elasticsearch.password=MyPwd123
    # volumes: 
    #   - /home/home/ELK/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    links: 
      [elasticsearch]
    depends_on: 
      [elasticsearch]
    expose: 
      - "5601"

  logstash:
    image: docker.elastic.co/logstash/logstash:${TAG}
    container_name: logstash
    # volumes: 
    #   - /home/home/ELK/logstash/pipeline/:/usr/share/logstash/pipeline/
    links: 
      [elasticsearch]
    depends_on: 
      [elasticsearch]

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
        - 8081:80
    volumes:
        - /home/home/ELK/nginx-config/:/etc/nginx/conf.d/
    command: /bin/bash -c "nginx -g 'daemon off;'"
    ulimits:
      nproc: 65535